// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PopulatioStats_core5.Models;

namespace PopulatioStats_core5.Migrations
{
    [DbContext(typeof(PopuContext))]
    partial class PopuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("PopulatioStats_core5.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("PopulatioStats_core5.Models.Population", b =>
                {
                    b.Property<int>("PopulationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("YearValId")
                        .HasColumnType("int");

                    b.HasKey("PopulationId");

                    b.HasIndex("CountryId");

                    b.HasIndex("YearValId");

                    b.ToTable("Populations");
                });

            modelBuilder.Entity("PopulatioStats_core5.Models.YearVal", b =>
                {
                    b.Property<int>("YearValId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PopulationId")
                        .HasColumnType("int");

                    b.Property<ulong>("Value")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("YearValId");

                    b.ToTable("YearVals");
                });

            modelBuilder.Entity("PopulatioStats_core5.Models.Population", b =>
                {
                    b.HasOne("PopulatioStats_core5.Models.Country", "country")
                        .WithMany("Populations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PopulatioStats_core5.Models.YearVal", "YearVals")
                        .WithMany("Populations")
                        .HasForeignKey("YearValId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");

                    b.Navigation("YearVals");
                });

            modelBuilder.Entity("PopulatioStats_core5.Models.Country", b =>
                {
                    b.Navigation("Populations");
                });

            modelBuilder.Entity("PopulatioStats_core5.Models.YearVal", b =>
                {
                    b.Navigation("Populations");
                });
#pragma warning restore 612, 618
        }
    }
}
